#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "zellner"
  colorscheme_bg = "light"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = false
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "fire"
  statusline_iseparator = "fire"
  buffer_index_type = 4
  windows_index_type = 3
  enable_tabline_filetype_icon = false
  enable_statusline_mode = false
  statusline_unicode_symbols = true
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = true
  # File Tree
  filemanager = "nerdtree"
  filetree_direction = "left"
  # Autocompletion
  autocomplete_method = "coc"

# FZF
[[layers]]
  name = "fzf"

# Enable autocomplete layer
[[layers]]
  name = "autocomplete"
  auto_completion_tab_key_behavior = "cycle"
  auto_completion_return_key_behavior = "complete"

# Shell Configuration
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# Activate Colorscheme
[[layers]]
  name = "colorscheme"

# Color Schemes
[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false

[[custom_plugins]]
  repo = "sainnhe/sonokai"
  name = "sonokai"
  merged = false

[[custom_plugins]]
  repo = "liuchengxu/vista.vim"
  name = "vista.vim"
  merged = false

[[custom_plugins]]
  repo = "lambdalisue/fern.vim"
  name = "fern.vim"
  merged = false

# Python
[[layers]]
  name = "lang#python"
  python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    ''
  ]

# Jupyter Noteboks
[[layers]]
  name = "lang#ipynb"

# HTML
[[layers]]
  name = "lang#html"

# LaTeX
[[layers]]
  name = "lang#latex"

# Scripts
[[layers]]
  name = "lang#sh"
