#!/bin/sh
#
# AUTHOR: Tanjona R. Rabemananjara
#
# DATE: Wed January 06 2021
#
# DESC: Elvi to search arXiv
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search arxiv for papers ugin keywords
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://arxiv.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://arxiv.org/search/?query=${escaped_args}&searchtype=all&source=header"
fi
